apiVersion: v1
kind: List
items:
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: kubenodes.bootsy.flyover.com
  spec:
    scope: Cluster
    group: bootsy.flyover.com
    version: v1
    names:
      kind: KubeNode
      plural: kubenodes
      singular: kubenode
      shortNames: [ kn ]
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: kubenodecontrollers.bootsy.flyover.com
  spec:
    scope: Cluster
    group: bootsy.flyover.com
    version: v1
    names:
      kind: KubeNodeController
      plural: kubenodecontrollers
      singular: kubenodecontroller
      shortNames: [ knc ]
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: kubenodeproviders.bootsy.flyover.com
  spec:
    scope: Cluster
    group: bootsy.flyover.com
    version: v1
    names:
      kind: KubeNodeProvider
      plural: kubenodeproviders
      singular: kubenodeproviders
      shortNames: [ knp ]
- apiVersion: bootsy.flyover.com/v1
  kind: KubeNode
  metadata:
    generateName: node-
    labels:
      type: master
  spec:
    type: master
    provider: bootstrap
    ipAddress: "$ip_address"
    version: "$version"
    connector:
      type: ssh
      authSecret:
        namespace: bootsy
        name: "$auth_secret_name"
- apiVersion: v1
  kind: Namespace
  metadata:
    name: bootsy
  spec:
    finalizers:
    - kubernetes
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: bootsy-operator
    namespace: bootsy
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: bootsy
      spec:
        containers:
        - name: bootsy-operator
          image: portr.ctnr.ctl.io/markramach/bootsy-operator:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          args:
          - "--bootsy.k8s.endpoint=http://$ip_address:8080"